name: dashboard_manga_easy
description: Painel administrativo para os autores, parceiros e admins do app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.4.0+1

environment:
  sdk: ">=3.0.5 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  #### PACKAGES ####
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.7
  appwrite: ^9.0.1
  get_it: ^7.6.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  octo_image: ^1.0.2
  package_info_plus: ^4.0.2
  dropdown_search: ^5.0.6
  intl: ^0.18.0
  dynamic_color: ^1.6.6
  infinite_scroll_pagination: ^3.2.0
  file_picker: ^5.3.2
  #### LIBS #####
  manga_easy_sdk:
  client_driver:
  coffee_cup:
  toggle_config:
  persistent_database:
  manga_easy_crashlytics_service:
  #### MICRO APPS #####
  manga_easy_advanced_search:
    git:
      url: https://github.com/manga-easy/manga_easy_advanced_search.git
      ref: v1.1.0

dependency_overrides:
  client_driver:
    git:
      url: https://github.com/manga-easy/manga_easy_client_driver.git
      ref: v1.2.0
  coffee_cup:
    git:
      url: https://github.com/manga-easy/manga_easy_coffee_cup.git
      ref: v1.3.1
  manga_easy_sdk:
    git: 
      url: https://github.com/manga-easy/manga_easy_sdk.git
      ref: v1.5.0
  toggle_config:
    git: 
      url: https://github.com/manga-easy/lib_toggle_config.git
      ref: v1.1.1
  persistent_database:
    git:
      url: https://github.com/manga-easy/lib_persistent_database.git
      ref: v1.2.2
  manga_easy_crashlytics_service:
    git:
      url: https://github.com/manga-easy/manga_easy_crashlytics_service.git
      ref: v1.0.0
  http: ^1.1.0 

dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.3.1

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  #branding: assets/branding-production.png
  color_dark: "#121212"
  #image_dark: assets/logo-production.png
  #branding_dark: assets/branding-production.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    #image_dark: assets/logo-production.png
    icon_background_color_dark: "#121212"
# flutter pub run flutter_native_splash:create
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
# flutter pub run flutter_launcher_icons:main


# relese
# flutter build web --release --web-renderer html