name: dashboard_manga_easy
description: Painel administrativo para os autores, parceiros e admins do app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.3.0+5

environment:
  sdk: ">=2.19.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^4.0.3
  flutter_svg: ^2.0.2
  dart_appwrite: 6.0.1
  appwrite: 7.0.0
  get_it: ^7.2.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  uuid: ^3.0.7
  octo_image: ^1.0.2
  package_info_plus: ^3.0.3
  dropdown_search: ^5.0.6
  api_fcm: ^1.1.1
  intl: ^0.18.0
  dynamic_color: ^1.6.2
  http: ^0.13.5
  html_editor_enhanced: 2.5.1
  infinite_scroll_pagination: ^3.2.0
  file_picker: ^5.2.5
  #### MICRO APPS #####
  manga_easy_advanced_search:
    git:
      url: https://github.com/manga-easy/manga_easy_advanced_search.git
      ref: v0.0.3
  manga_easy_sdk:
    git:
      url: https://github.com/manga-easy/manga_easy_sdk.git
      ref: v.0.11.x
  client_driver:
    git:
      url: https://github.com/manga-easy/manga_easy_client_driver.git
      ref: 0.0.1
  coffee_cup:
    git:
      url: https://github.com/manga-easy/manga_easy_coffee_cup.git
      ref: v0.11.x
dependency_overrides:
  package_info_plus: ^3.0.3

dev_dependencies:
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.12.0
  flutter_native_splash: ^2.2.18

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
  #   - images/a_dot_ham.jpeg
flutter_native_splash:
  color: "#ffffff"
  image: assets/images/logo.png
  #branding: assets/branding-production.png
  color_dark: "#121212"
  #image_dark: assets/logo-production.png
  #branding_dark: assets/branding-production.png

  android_12:
    image: assets/images/logo.png
    icon_background_color: "#ffffff"
    #image_dark: assets/logo-production.png
    icon_background_color_dark: "#121212"
# flutter pub run flutter_native_splash:create
flutter_icons:
  android: true
  ios: false
  image_path: "assets/images/logo.png"
  adaptive_icon_background: "#ffffff"
# flutter pub run flutter_launcher_icons:main


# relese
# flutter build web --release --web-renderer html