name: dashboard_manga_easy
description: Painel administrativo para os autores, parceiros e admins do app

publish_to: "none" # Remove this line if you wish to publish to pub.dev

version: 1.7.0+15

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  #### PACKAGES ####
  google_fonts: ^6.2.1
  flutter_svg: ^2.0.7
  appwrite: ^12.0.4
  get_it: ^7.6.0
  octo_image: ^2.0.0
  package_info_plus: ^8.0.2
  dropdown_search: ^5.0.6
  intl: ^0.19.0
  infinite_scroll_pagination: ^4.0.0
  file_picker: ^8.0.3
  logger: ^2.1.0
  dio: ^5.4.1
  hive: ^2.2.3
  path_provider: ^2.1.2
  path: ^1.9.0
  flutter_cache_manager: ^3.3.1
  image_picker: ^1.0.7
  mime: ^1.0.5
  http_parser: ^4.0.2
  jwt_decoder: ^2.0.1
  sembast: ^3.7.1+2
  uuid: ^4.4.0
  hive_flutter: ^1.1.0
  page_manager:
    git:
      url: https://github.com/lucascardo12/page_manager.git
      ref: 0.0.2
  go_router: ^14.2.0

dev_dependencies:
  flutter_lints: ^4.0.0
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  flutter_native_splash: ^2.4.0

flutter:
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
flutter_native_splash:
  android: false
  ios: false
  color: "#ffffff"
  image: assets/images/logo.png
  color_dark: "#121212"

# flutter pub run flutter_native_splash:create
flutter_launcher_icons:
  android: false
  ios: false
  image_path: "assets/images/logo.png"
  web:
    generate: true
    background_color: "#ffffff"
    # theme_color: "#hexcode"

# flutter pub run flutter_launcher_icons:main


# relese
# flutter build web --release --web-renderer html --no-tree-shake-icons
# flutter build apk --release --no-tree-shake-icons
# flutter build windows --release --no-tree-shake-icons